stages:
  - build
  - archive

build_project:
  stage: build
  script: 
    - xcodebuild clean build -sdk iphonesimulator -workspace iosu.xcworkspace -scheme iosu CODE_SIGNING_REQUIRED=NO
  only:
   - tags
   - triggers

archive_project:
  stage: archive
  script: 
    - xctool -project iosu.xcodeproj -scheme iosu archive -archivePath build/iosu
    - xcodebuild -exportArchive -exportFormat ipa -archivePath "build/iosu.xcarchive" -exportPath "build/iosu.ipa"
  only: 
    - tags
    - triggers
  artifacts:
    paths:
      - build/iosu.ipa