stages:
  - build
  - archive

build_project:
  stage: build
  script: 
    - pod install
    - xcodebuild clean build -sdk iphonesimulator -workspace iosu.xcworkspace -scheme iosu CODE_SIGNING_REQUIRED=NO
  only:
   - tags
   - triggers

archive_project:
  stage: archive
  script: 
    - xcodebuild archive -workspace iosu.xcworkspace -scheme iosu -destination generic/platform=iOS -archivePath build/iosu.xcarchive
    - xcodebuild -exportArchive -archivePath build/iosu.xcarchive -exportPath build -exportOptionsPlist ipa.plist
  only: 
    - tags
    - triggers
  artifacts:
    paths:
      - build/iosu.ipa