language: objective-c
osx_image: xcode8.3
xcode_project: iosu.xcworkspace
xcode_scheme: iosu
xcode_sdk: iphonesimulator10.0
script:
 - xcodebuild clean build -sdk iphonesimulator -workspace iosu.xcworkspace -list
 - xcodebuild clean build -sdk iphonesimulator -workspace iosu.xcworkspace -scheme iosu CODE_SIGNING_REQUIRED=NO
